@echo off
echo Removing current build...
del ZAMN_SuperFamicade.sfc
echo Copying original (Base) ROM...
copy ".\base\Zombies Ate My Neighbors (USA).sfc" ZAMN_SuperFamicade.sfc
echo Building...
..\Tools\xkas\xkas.exe ZAMN_HUD_Expansion_v2.asm .\out\ZAMN_SuperFamicade.sfc
echo Done.